[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "netbox-circuit-maintenance"
version = "0.1.0"
requires-python = ">=3.12.0"
authors = [
	{name = "Charles Flanders", email = "cflanders@capitalpower.com"},
]
description = "Automatically handle Circuit Maintenance emails in NetBox"
readme = { file = "README.md", content-type = "text/markdown" }
license-files = ["LICENSE"]
keywords = ["netbox", "netbox-plugin"]
classifiers = [
	"Development Status :: 3 - Alpha",
	"Framework :: Django",
	"Framework :: Django 6",
	"Intended Audience :: Developers",
	"Intended Audience :: System Administrators",
	"Intended Audience :: Telecommunication Industry",
	"License :: OSI Approved :: Apache Software License",
	"Natural Language :: English",
	"Operating System :: OS Independent",
	"Programming Language :: Python",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3 :: Only",
	"Programming Language :: Python :: 3.12",
	"Programming Language :: Python :: 3.13",
	"Programming Language :: Python :: 3.14",
	"Topic :: System :: Networking",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
# Include the root package *and* any subpackages we add later (api/, graphql/, etc)
include = ["netbox_circuit_maintenance*"]

[tool.setuptools.package-data]
netbox_circuit_maintenance = [
	"templates/**",
	"static/**",
	"locale/**/*.mo"
]

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = [
	"E",
	"W",
	"F",
	"I",
	"B",
	"C4",
	"UP",
]
ignore = [
	"E501",
	"B008",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
